---
- hosts: nodes
  user: root
  tasks:
     - name: insert master and slave ip into hosts
       lineinfile: dest=/etc/hosts line="{{ item }}" state=present
       with_items:
         - "{{ lines }}"
       sudo: yes
