---
- hosts: '{{hosts}}'
  user: root
  vars:
     ansible_become_pass: root
     dir: /home/rczkp01/zookeeper/data/myid
  tasks:
     - name: create zookeeper data directory
       file: path=/home/rczkp01/zookeeper/data state=directory owner=root mode=0755 recurse=yes
       sudo: yes
     - name: create zookeeper log directory
       file: path=/home/rczkp01/zookeeper/log state=directory owner=root mode=0755 recurse=yes
     - name: creat myid file
       file: path={{dir}} state=touch owner=root mode=0744
       sudo: yes
     - name: assign a integer value to myid
       lineinfile: dest={{dir}} line={{myid}}
       sudo: yes
     - name: start zookeeper service 
       service: name=zookeeper state=restarted  enabled=yes
       sudo: yes
