---
- hosts: slave
  gather_facts: false
  user: root
  tasks:
    - wait_for: host={{ item }} port=2181 state=started delay=1
      with_items:
         - "{{ inventory_hosts }}"
      sudo: yes
    - shell: echo stat | nc {{ item }} 2181
      with_items:
         - "{{ inventory_hosts }}"
      register: status
      failed_when: status.rc != 0
      sudo: yes
