---
- hosts: '{{ hosts }}'
  user: rcflannel
  tasks:
     - name: publish flannel config to etcd
       command: "etcdctl -C='{{ etcdhost }}' set /coreos.com/network/config '{\"Network\": \"172.18.0.0/16\", \"Backend\": { \"Type\": \"vxlan\",\"Port\": 8472 } }'"
       sudo: yes
