---
- hosts: '{{ hosts }}'
  user: root
  tasks:
     - name: publish flannel config to etcd
       command: "etcdctl -C='{{ etcdhost }}' set {{ path }} '{\"Network\": \"{{ subnet }}\", \"Backend\": { \"Type\": \"vxlan\",\"Port\": 8472 } }'"
       sudo: yes
