--- 
- hosts: master
  user: root
  vars:
     software: ['mesosphere-zookeeper','mesos','marathon','flannel','etcd','chronos','docker-engine']
     services: ['zookeeper','mesos-master','marathon','flannel','etcd','chronos','docker']
     users: ['rczkp01','rcmesos','rcmarathon','rcflannel','rcchronos','rcdns']
     installpath: ['/usr/bin/mesos-dns','/usr/local/bin/consul','/etc/systemd/system/consul.service','/etc/systemd/system/mesos-dns.service']
     datapath: ['/var/log/mesos','/opt/consul','/var/lib/etcd','/etc/zookeeper','/etc/mesos','/etc/mesos-master','/etc/marathon','/etc/consul','/tmp/mesos']
  tasks:
     - name: stop software service
       service: name={{ item }} state=stopped
       with_items:
         - "{{ services }}"
     - name: remove software installed by yum
       yum: name={{ item }} state=absent
       with_items:
         - "{{ software }}"
     - name: remove users created
       user: name={{ item }} state=absent remove=yes
       with_items:
         - "{{ users }}"
     - name: stop consul and mesos-dns
       command: systemctl stop {{ item }}
       with_items:
         - consul
         - mesos-dns
     - name: remove mesos-dns and consul
       file: path={{ item }} state=absent
       with_items:
         - "{{ installpath }}"
       sudo: yes

     - name: remove consul's data and log
       file: path={{ item }} state=absent
       with_items:
         - "{{ datapath }}"
       sudo: yes
     - name: delete zookeeper param
       lineinfile: dest=/etc/profile regexp=zookeeper? state=absent
       sudo: yes
     - name: delete userinfo in sudoers
       lineinfile: dest=/etc/sudoers regexp={{ item }}? state=absent
       with_items:
         - "{{ users }}"
       sudo: yes
     - name: delete docker path
       file: path={{ dockerpath }} state=absent
       sudo: yes
