---
- hosts: '{{ hosts }}'
  user: root
  vars:
     dest: /etc/keepalived/keepalived.conf
  tasks:
     - name: yum install haproxy
       yum: name=haproxy state=latest
       sudo: yes
     - name: yum install keepalived
       yum: name=keepalived state=latest
       sudo: yes
     - name: mv keepalived.conf
       command: mv /etc/keepalived/keepalived.conf /etc/keepalived/keepalived.conf.bak
     - name: transfer keepalived.conf to the dest hosts
       copy: src={{ configfile }} dest=/etc/keepalived/keepalived.conf owner=root  mode=0755
     - name: transfer check_haproxy.sh to the dest hosts
       copy: src={{ checkshell }} dest=/etc/keepalived/check_haproxy.sh owner=root  mode=0755
     - name: transfer check_haproxy.cfg to the dest hosts
       copy: src={{ haconfig }} dest=/etc/haproxy/haproxy.cfg owner=root  mode=0755
     - name: insert state to the keepalived.conf
       lineinfile: dest={{ dest }} line="    state {{ role }}" state=present insertafter="interface?"
     - name: insert priority info
       lineinfile: dest={{ dest }} line="    priority {{ priority }}" state=present insertafter="virtual_router_id?"
     - name: insert virtual ip info
       lineinfile: dest={{ dest }} line="    {{ ip }}" state=present insertafter="virtual_ipaddress?"
     - name: restart haproxy service
       service: name=haproxy state=restarted enabled=yes
       sudo: yes
     - name: restart keepalived service
       service: name=keepalived state=restarted enabled=yes
       sudo: yes
