---
- hosts: slave
  user: rcflannel
  vars:
     flanneletcdkey: FLANNEL_ETCD_KEY="/coreos.com/network"
     execstart: ExecStart=/usr/bin/docker daemon -H fd:// $DOCKER_OPTS $DOCKER_OPT_BIP $DOCKER_OPT_MTU $DOCKER_OPT_IPMASQ
  tasks:
     - name: yum install flannel
       yum: name=flannel state=latest
       sudo: yes
     - name: change flannel-etcd
       lineinfile: dest=/etc/sysconfig/flanneld line="{{flanneletcd}}"  regexp='^FLANNEL_ETCD?' state=present
       sudo: yes
     - name: change flannel-etcd-key
       lineinfile: dest=/etc/sysconfig/flanneld line="{{flanneletcdkey}}" regexp='^FLANNEL_ETCD_KEY?' state=present
       sudo: yes
     - name: modify docker.service
       lineinfile: dest=/usr/lib/systemd/system/docker.service line="{{execstart}}" regexp='ExecStart?' state=present
     - name: restart flannel
       service: name=flanneld state=restarted
       sudo: yes
     - name: reload daemon-reload
       command: systemctl daemon-reload
       sudo: yes
     - name: restart docker
       service: name=docker state=restarted
       sudo: yes
