---
- hosts: master
  user: root
  vars: 
  tasks:
      - name: open port 
        command: firewall-cmd --zone=public --add-port={{item}}/tcp --permanent
        with_items:
           - "{{ ports }}"
        sudo: yes
      - name: reload firewall-cmd
        command: firewall-cmd --reload
        sudo: yes
