---
- hosts: master
  user: rcmarathon
  vars:
      ansible_become_pass: root
      subscriber: http_callback
  tasks:
      - name: yum install marathon
        yum: name=marathon state=latest
        sudo: yes
      - name: create dir /etc/marathon/conf
        file: path=/etc/marathon/conf state=directory mode=0755
        sudo: yes
      - name: echo event_subscriber
        shell: echo "{{subscriber}}" > event_subscriber
        args:
             chdir: /etc/marathon/conf
        sudo: yes
      - name: echo master
        shell: echo "{{master}}" > master
        args:
             chdir: /etc/marathon/conf
        sudo: yes
      - name: echo zk 
        shell: echo "{{zk}}" > zk
        args:
             chdir: /etc/marathon/conf
        sudo: yes
      - name: open 8080 port
        firewalld: port={{ item }}/tcp permanent=true state=enabled
        with_items:
                - 8080
        sudo: yes
      - name: reload firewall-cmd
        command: firewall-cmd --reload
        sudo: yes
