---
- hosts: master
  user: rcconsul
  vars:
      ansible_become_pass: root
      subscriber: http_callback
  tasks:
      - name: yum install consul
        yum: name=consul state=latest
        sudo: yes
      - name: create dir /etc/consul.d
        file: path=/etc/consul.d state=directory mode=0755
        sudo: yes
      - name: echo event_subscriber
        shell: echo "{{subscriber}}" > event_subscriber
        args:
             chdir: /etc/consul.d
        sudo: yes
      - name: echo master
        shell: echo "{{master}}" > master
        args:
             chdir: /etc/consul.d
        sudo: yes
      - name: open 8600 port
        firewalld: port={{ item }}/tcp permanent=true state=enabled
        with_items:
                - 8600
        sudo: yes
      - name: reload firewall-cmd
        command: firewall-cmd --reload
        sudo: yes
