---
- hosts: slave
  user: root
  vars: 
  tasks:
      - name: open tcp port 
        firewalld: port={{ item }}/tcp permanent=true state=enabled
        with_items:
           - "{{ ports }}"
        sudo: yes
      - name: open udp port 
        firewalld: port={{ item }}/udp permanent=true state=enabled
        with_items:
           - "{{ ports }}"
        sudo: yes
      - name: reload firewall-cmd
        command: firewall-cmd --reload
        sudo: yes
